In [22]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

import pandas as pd
import numpy as np

x = np.array([1,2,3,4,5,6,7,8,9,10])
y = np.array([2,4,6,8,10,12,14,16,18,20])

In [23]:
import tensorflow as tf

model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(32, input_dim=1))
model.add(tf.keras.layers.Dense(16, activation='relu'))
model.add(tf.keras.layers.Dense(1))

model.compile(loss='mean_squared_error', optimizer='adam',metrics=['accuracy'])

In [24]:
hist = model.fit(x, y, epochs=100, batch_size=1)

Epoch 1/100
10/10 [==============================] - 0s 992us/step - loss: 203.2474 - accuracy: 0.0000e+00
Epoch 2/100
10/10 [==============================] - 0s 977us/step - loss: 186.8105 - accuracy: 0.0000e+00
Epoch 3/100
10/10 [==============================] - 0s 929us/step - loss: 170.3026 - accuracy: 0.0000e+00
Epoch 4/100
10/10 [==============================] - 0s 1ms/step - loss: 156.4497 - accuracy: 0.0000e+00
Epoch 5/100
10/10 [==============================] - 0s 812us/step - loss: 147.5621 - accuracy: 0.0000e+00
Epoch 6/100
10/10 [==============================] - 0s 769us/step - loss: 142.7865 - accuracy: 0.0000e+00
Epoch 7/100
10/10 [==============================] - 0s 732us/step - loss: 138.9018 - accuracy: 0.0000e+00
Epoch 8/100
10/10 [==============================] - 0s 776us/step - loss: 133.9426 - accuracy: 0.0000e+00
Epoch 9/100
10/10 [==============================] - 0s 736us/step - loss: 127.4732 - accuracy: 0.0000e+00
Epoch 10/100
10/10 [===================

In [25]:
y_predict = model.predict([1])
y_predict

array([[2.3546195]], dtype=float32)

In [26]:
model.save("resource/model/test.h5")

In [53]:
model2 = tf.keras.models.load_model("resource/model/test.h5")

In [54]:
y_predict2 = model2.predict([1])
y_predict2

array([[2.3546195]], dtype=float32)

In [55]:
# x2 = np.array([1,2,3,4,5,6,7,8,9,10])
# y2 = np.array([4,8,12,16,20,24,28,32,36,40])

x2 = np.array([1,2,3,4,5])
y2 = np.array([4,8,12,16,20])

x3 = np.array([6,7,8,9,10])
y3 = np.array([24,28,32,36,40])

In [57]:
hist = model2.fit(x3, y3, epochs=50, batch_size=1)

Epoch 1/50
5/5 [==============================] - 0s 938us/step - loss: 1.8705 - accuracy: 0.0000e+00
Epoch 2/50
5/5 [==============================] - 0s 1ms/step - loss: 0.3009 - accuracy: 0.0000e+00
Epoch 3/50
5/5 [==============================] - 0s 1ms/step - loss: 0.4887 - accuracy: 0.0000e+00
Epoch 4/50
5/5 [==============================] - 0s 1ms/step - loss: 0.3165 - accuracy: 0.0000e+00
Epoch 5/50
5/5 [==============================] - 0s 936us/step - loss: 0.0773 - accuracy: 0.0000e+00
Epoch 6/50
5/5 [==============================] - 0s 932us/step - loss: 0.1615 - accuracy: 0.0000e+00
Epoch 7/50
5/5 [==============================] - 0s 935us/step - loss: 0.1063 - accuracy: 0.0000e+00
Epoch 8/50
5/5 [==============================] - 0s 1ms/step - loss: 0.0518 - accuracy: 0.0000e+00
Epoch 9/50
5/5 [==============================] - 0s 1ms/step - loss: 0.0646 - accuracy: 0.0000e+00
Epoch 10/50
5/5 [==============================] - 0s 1ms/step - loss: 0.0601 - accuracy: 0.

In [58]:
y_predict2 = model2.predict([1])
y_predict2

array([[4.9540358]], dtype=float32)

In [145]:


# Calling `save('my_model.h5')` creates a h5 file `my_model.h5`.


# It can be used to reconstruct the model identically.
# reconstructed_model = keras.models.load_model("my_h5_model.h5")

In [ ]:
import numpy as np
def create_dataset(signal_data, look_back=1):
    x_arr, y_arr = [], []
    for i in range(len(signal_data) - look_back):
        x_arr.append(signal_data[i:(i + look_back), 0])
        y_arr.append(signal_data[i + look_back, 0])

    x_arr = np.array(x_arr)
    x_arr = np.reshape(x_arr, (x_arr.shape[0], x_arr.shape[1], 1))
    return x_arr, np.array(y_arr)

klines_dataset = pd.read_csv('resource/dataset/binance/klines-BTCUSDT-1m_20220101090000_20220101205900.csv').to_numpy()

# 훈련
train = klines_dataset[0:int(len(klines_dataset) * 0.5)]
# 검증
val = klines_dataset[int(len(klines_dataset) * 0.5):int(len(klines_dataset) * 0.75)]
# 시험
test = klines_dataset[int(len(klines_dataset) * 0.75):-1]

x_train, y_train = create_dataset(train, look_back)
x_val, y_val = create_dataset(val, look_back)
x_test, y_test = create_dataset(test, look_back)
